#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int globalSpeed = 70;
int buttonStatus = 0; //0 - none//1-6D//2-6U//3-5U//4-5D

task main()
{
	while(true){ //infinite while loop

		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
		if (vexRT[Btn6D] == 1){
			buttonStatus = 1;

		}
		else if (vexRT[Btn6U] == 1){
			buttonStatus = 2;

		}
		else if (vexRT[Btn5D] == 1){
			buttonStatus = 3;

		}
		else if (vexRT[Btn5U] == 1){
			buttonStatus = 4;

		}
		else {
			buttonStatus = 0;

		}
		switch buttonStatus{

		case 1:
			motor[armMotor] = -globalSpeed;
			break;

		case 2:
			motor[armMotor] = globalSpeed;
			break;

			case 3;
			motor[clawMotor] = globalSpeed;
			break;

		case 4:
			motor[clawMotor] = -globalSpeed;
			break;

		}
	}
}
